### ISSUE TITLE
run_eval mini-imagenet

### ISSUE THREAD

**Issue by YizhaoGao-AI** [k-r-allen/imp#2]
Thanks for your remarkable work! Could you give an example to run 'imp' model on 'miniImageNet' like the "submit_omniglot.sh" file ?

**Comment by SnowZhao-wazi** [comment]
Thanks for sharing the code. I have a question about the .pkl data. When I loaded the .pkl file, I found the data was a list of numpy arrays without _category_labels information. Did I miss something? I download the data from https://drive.google.com/file/d/1INlOTyPtnCJgm0hBVvtRLu5a0itk8bjs/view.

**Comment by k-r-allen** [comment]
Thank you for looking! You should be able to just change the "omniglot" dataset name to "mini-imagenet" with no further changes required. As long as you have the mini-imagenet dataset (which you can get by looking at this repository: https://github.com/renmengye/few-shot-ssl-public), everything else should work out of the box.
