### ISSUE TITLE
Filepath issues with data

### ISSUE THREAD

**Issue by sathvikn** [k-r-allen/imp#5]
I tried to adapt my filepath for the `data-root` parameter in `submit_omniglot.sh`, but I can't find the actual Omniglot data. Is this included with the repo? If not, where can we find it? Thank you!

**Comment by k-r-allen** [comment]
Hi, sorry for the delay! The actual omniglot data is not provided with this repo. You can find it here: https://drive.google.com/file/d/1INlOTyPtnCJgm0hBVvtRLu5a0itk8bjs/view

**Comment by sathvikn** [comment]
No worries, thanks so much for responding! I tried running the script, but now I'm running into an error that gets caused because the field `category_labels` isn't in the pickle file. Any reason why this may be the case?

EDIT: I was able to work around this by passing `self._labels` into the call to `process_category_labels` in the `read_cache` function from `omniglot.py. I'm not sure if that's correct so would appreciate confirmation.

EDIT 2: With this fix I implemented I got an accuracy of 97.7% but I'm not sure which figure in the paper this refers to. Thanks so much for the clarifications!

**Comment by k-r-allen** [comment]
Try removing the .pkl files and just keeping the image folders, it should re-generate the pkl files and those should have category labels!

**Comment by sathvikn** [comment]
Hmm, I'm not able to see the image folders, would they be in `DATA_ROOT`?  This is where I unzipped the omniglot data. 
 
<img width="1229" alt="Screen Shot 2020-07-28 at 2 44 56 PM" src="https://user-images.githubusercontent.com/23415060/88725618-3d20cc00-d0e1-11ea-8a93-cea2e575cbc1.png">

**Comment by hannajiang** [comment]
I also meet this problem. Have you solved the problem yet?
